name: Secret Generator

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ production, sandbox ]

env:
  ORG_NAME: ACE-Lan

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Get branch
      - name: Get branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        
      - name: Configure Environment
        uses: ACE-Lan/sf-environments-action@main
        with:
          action: write
          token: ${{ secrets.SECRET_GENERATOR_TOKEN }}
          org: ${{ env.ORG_NAME }}
          environment: ${{ env.BRANCH_NAME }}
